### ISSUE TITLE
oonimkall: setRunType: cannot find symbol

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe#2110]
Linking with the oonimkall.aar engine fails with this error:

```
> Task :engine:compileExperimentalReleaseJavaWithJavac FAILED
$monorepo/repo/probe-android/engine/src/main/java/org/openobservatory/engine/OONICheckInConfig.java:67: error: cannot find symbol
        c.setRunType(runType);
         ^
  symbol:   method setRunType(String)
  location: variable c of type CheckInConfig
1 error

FAILURE: Build failed with an exception.
```

We need to fix this error in order to release 3.15.0.

(cc: @hellais @aanorbel)

**Comment by bassosimone** [comment]
The reason why this new error popped up is now apparent if we look at the generated Java file:

```Java
public final class CheckInConfig implements Seq.Proxy {
        // ...

        // skipped field CheckInConfig.RunType with unsupported type: github.com/ooni/probe-cli/v3/internal/model.RunType

        // ...
}
```

To fix, we need to change the type to belong to the same package and/or switch directly to string.

The error was introduced by https://github.com/ooni/probe-cli/pull/714.

**Comment by bassosimone** [comment]
Fixed both in the main branch and in the release/3.15 branch.
